CallForRent/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('home.urls')),
    url(r'', include('authentication.urls')),
    url(r'posts/', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name = 'authentication'

urlpatterns = [
 path('signin/', views.SignInView, name='signin'),
 path('signout/', views.LogoutView, name='signout'),
 path('register/', views.SignUpView, name='register'),
]

home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'

urlpatterns = [
    #  / home/
    url(r'^$', views.homeView, name='home'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import redirect, render, HttpResponse

def homeView(request):
    return render(request, 'home/homepage.html')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">


{#    {% load staticfiles %}#}
{#    <link rel="stylesheet" type="text/css" href="{% static "home/style.css" %}">#}
{#    <link rel="stylesheet" type="text/css" href="{% static "home/home_style.css" %}">#}

                {#  BootStrap 4 files   #}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>





                {# Extra Styles #}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    {% block title %}

    <title>Home page</title>                    {#Title Block#}

    {% endblock %}

</head>


<body>

<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:home' %}">CallForRent</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
    </ul>
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:signin' %}">Login</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:register' %}">SignUp</a>
      </li>
    </ul>
{#    <form class="form-inline my-2 my-lg-0">#}
{#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#    </form>#}
  </div>


</nav>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="2000">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" style="background-color: aqua; height: 350px">
      <img class="d-block w-100" src="media/friends.jpg" alt="First slide">
    </div>
    <div class="carousel-item" style="background-color: aqua; height: 350px">
      <img class="d-block w-100" src="media/dr.jpg" alt="Second slide">
    </div>
    <div class="carousel-item" style="background-color: aqua; height: 350px">
      <img class="d-block w-100" src="media/got.jpg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% include 'home/messages_display.html' %}
<div class="container">
    {% block content %}

    {% endblock content %}
</div>

</body>
</html>

home/templates/home/homepage.html
{% extends 'home/base.html' %}
{% load static %}


{% block title %}
    <title>Home_Page</title>
{% endblock %}

home/templates/home/messages_display.html
{% if messages %}
    <div class="alert alert-warning alert-dismissable" role="alert">
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    </div>
{% endif %}