CallForRent/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('home.urls')),
    url(r'', include('authentication.urls')),
    url(r'posts/', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name = 'authentication'

urlpatterns = [
 path('signin/', views.SignInView, name='signin'),
 path('signout/', views.LogoutView, name='signout'),
 path('register/', views.SignUpView, name='register'),
]

home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'

urlpatterns = [
    #  / home/
    url(r'^$', views.homeView, name='home'),
]

posts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('create/', views.posts_create, name='create'),
    path('<int:id>/', views.posts_detail, name='detail'),
    path('<int:id>/edit/', views.posts_update, name='update'),
    path('<int:id>/delete/', views.posts_delete, name='delete'),

]

posts/models.py
from __future__ import unicode_literals
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=120)
    image = models.ImageField(null=True, blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    time_stamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.title
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/posts/%s/" %(self.id)


    class Meta:
        ordering = ["-time_stamp", "-updated"]

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
        ]

posts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.db.models import Q
from .forms import PostForm
from authentication.models import User

@login_required(login_url='/signin/')
def posts_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        print(form.cleaned_data.get("title"))
        instance.save()
        messages.success(request, "Successfully created")
        return HttpResponseRedirect(instance.get_absolute_url())
    # if request.method == "POST":
    #     print(request.POST)
    context = {
        "form": form,
    }
    return render(request, 'posts/post_form.html', context)

@login_required(login_url='/signin/')
def posts_detail(request,id=None):
    #instance = Post.objects.get(id=5)
    instance = get_object_or_404(Post, id=id)

    context = {
        "title": instance.title,
        "instance": instance,
    }
    return render(request, 'posts/post_detail.html', context)
@login_required(login_url='/signin/')
def posts_list(request):
    user = request.user
    queryset = Post.objects.all() #.order_by("-time_stamp")
    query = request.GET.get("q")
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query)
        ).distinct()
    context = {
        "object_list": queryset,
        "title": "List",
        'user': user,
    }
    return render(request, 'posts/index.html', context)
@login_required(login_url='/signin/')
def posts_update(request, id=None):
    instance = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "saved")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }
    return render(request, 'posts/post_form.html', context)
@login_required(login_url='/signin/')
def posts_delete(request, id=None):
    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, "susccesfully deleted")
    return redirect("posts:list")

posts/templates/posts/index.html
{% extends 'posts/post_base.html' %}
{% load static %}

{% block content %}

    <div>
    {% if user.is_authenticated %}
        <p>Username: {{ user.email }}</p>
    {% endif %}
    </div>
    <div class="col-sm-6 col-sm-offset-3" style="margin-bottom: 100px">
     <h1>{{ title }}</h1>
    <form method="get" action="">
    <input type="text" name="q" placeholder="Search Posts" value="{{ request.GET.q }}">
    <input type="submit" value="Search">

    </form>
    </div>

     {# SUB Menu Area           START#}
    <div class="container d-flex justify-content-center col-md-12" style="margin-bottom: 100px">
    <div class="d-flex justify-content-center mt-2 mb-2" style="margin-bottom: 100px" >
         <div class="td col-md-6" id="m-col">
             <div class="m-mrg" id="p-tabs">
                 <div class="tb">
                     <div class="td">
                         <div class="tb justify-content-center" id="p-tabs-m" style="display: flex">
                             <div class="td" style="margin-right:50px "><a id="u_link" class="a_link" href="{% url 'posts:create' %}"><i class="material-icons">create</i><span>Create_Post</span></a></div>
                             <div class="td"><a id="u_link" class="a_link" href="{% url 'posts:list' %}"><i class="material-icons">menu_book</i><span>Post_List</span></a></div>
{#                             <div class="td"><a id="u_link" class="a_link" href="{% url 'upload_app:add-album' %}"><i class="material-icons">file_upload</i><span>UPLOAD</span></a></div>#}
{#                             <div class="td"><a id="u_link" class="a_link" href="{% url 'friends:ViewFriends' %}"><i class="material-icons">message</i><span>REQUESTS</span></div>#}
{#                             <div class="td"> <a id="u_link" class="a_link" href="{% url 'profile_app:profile-update' %}"><i class="material-icons">create</i><span>EDIT PROFILE</span></a></div>#}
                         </div>
                     </div>
                 </div>
             </div>
        </div>
    </div>
    </div>

    {# SUB Menu Area           END #}

    <div class="col-sm-6 col-sm-offset-3" style="margin: auto">
    {% for object in object_list %}
        <div class="row">
      <div class="col-sm-12">
        <div class="thumbnail">
            {% if object.image %}
                <img src="{{ object.image.url }}" class="img-responsive"/>
            {% endif %}
          <div class="caption" style="margin-bottom: 30px">
            <h3><a href='{{ object.get_absolute_url }}'>{{ object.title }}</a> <small>{{ object.time_stamp | timesince }}</small></h3>
            <p>{{ object.content | linebreaks | truncatechars:120 }}</p>
            <p><a href="{{ object.get_absolute_url }}" class="btn btn-primary" role="button">View</a> </p>
          </div>
        </div>
      </div>
        <hr/>
        </div>
        <hr/>

    {% endfor %}
    </div>

{% endblock content %}

posts/templates/posts/messages_display.html
{% if messages %}
    <div class="messages">
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    </div>
{% endif %}

posts/templates/posts/post_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">


{#    {% load staticfiles %}#}
{#    <link rel="stylesheet" type="text/css" href="{% static "home/style.css" %}">#}
{#    <link rel="stylesheet" type="text/css" href="{% static "home/home_style.css" %}">#}

                {#  BootStrap 4 files   #}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>





                {# Extra Styles #}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    {% block title %}

    <title>Posts</title>                    {#Title Block#}

    {% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="margin-bottom: 20px">
  <a class="navbar-brand" href="#">CallForRent</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:list' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
      <li class="nav-item">
        <a class="nav-link" href="#">Contack</a>
      </li>
    </ul>
    </ul>
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentication:signout' %}">Logout</a>
      </li>
      </ul>
{#    <form class="form-inline my-2 my-lg-0">#}
{#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#    </form>#}
  </div>
</nav>


{% include 'posts/messages_display.html' %}
<div class="container" style="background-color: azure">
    {% block content %}

    {% endblock content %}
</div>

</body>
</html>

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% load static %}

{% block head %} {{ instance.title }} | {{ block.super }} {% endblock head %}

{% block content %}

    <div class="col-sm-6 col-sm-offset-3">
    {% if instance.image %}
        <img src="{{ instance.image.url }}" class="img-responsive"/>
    {% endif %}

    <h1>{{ instance.title }} <small>{{ instance.time_stamp | timesince }}</small></h1>
    {{ instance.content | linebreaks }}<br/>

    </div>

{% endblock content %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load static %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
    <h1>Form</h1>
    <form method='POST' action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-outline-success my-2 my-sm-0" value="Create Post"/>
    </form>
    </div>
{% endblock content %}